First iteration
Dimabolt1985/go-db-sql-final pull request #1
Opened 2024-05-07 21:17 UTC by Dimabolt1985

2024-05-07 22:44 UTC, dirtymew requested changes
Привет Дмитрий

отличная работа , но есть что доделать 

см PR

2024-05-07 22:44 UTC, dirtymew commented on parcel.go
> +		return p, err
лучше явно пустую структуру вернуть

2024-05-07 22:44 UTC, dirtymew commented on parcel.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-05-07 22:44 UTC, dirtymew commented on parcel.go
> +	_, err := s.db.Exec("UPDATE parcel SET Address = :Address WHERE Number = :Number and Status = :Status",
ага супер - все одним запросом

2024-05-07 22:44 UTC, dirtymew commented on parcel_test.go
> +	assert.Equal(t, p, parcel)
когда пишем тесты их потом мы запускаем и работу отправляем на проверку когда тесты все проходят

сейчас падают - нужно поправить

2024-05-13 18:52 UTC, Dimabolt1985 commented
корректировка ошибок

2024-05-13 18:53 UTC, merged

2024-05-14 00:05 UTC, dirtymew reviewed
Привет Дмитрий 

работа выполнена - зачет

но больше PR не мержи до конца ревью